### ISSUE TITLE
hexo g command get error TypeError: this._items[key].slice is not a function

### ISSUE THREAD

**Issue by wangshuai-007** [dimaslanjaka/hexo-seo#24]
after run `hexo g` command
I will get the follow error:
```bash
INFO  Validating config
ERROR {
  err: TypeError: this._items[key].slice is not a function
      at NamespacePrefixMap.copy (D:\学习\Hexo\wangshuai-blog\node_modules\@oozcitak\dom\lib\serializer\NamespacePrefixMap.js:36:52)
      at BaseWriter._serializeElementNS (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\BaseWriter.js:341:29)
      at BaseWriter._serializeNodeNS (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\BaseWriter.js:220:22)
      at BaseWriter._serializeDocumentNS (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\BaseWriter.js:828:22)
      at BaseWriter._serializeNodeNS (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\BaseWriter.js:223:22)
      at BaseWriter.serializeNode (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\BaseWriter.js:201:18)
      at ObjectWriter.serialize (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\writers\ObjectWriter.js:79:14)
      at XMLBuilderImpl._serialize (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\builder\XMLBuilderImpl.js:671:27)
      at XMLBuilderImpl.end (D:\学习\Hexo\wangshuai-blog\node_modules\xmlbuilder2\lib\builder\XMLBuilderImpl.js:596:27)
      at initSitemap (D:\学习\Hexo\wangshuai-blog\node_modules\hexo-seo\dist\src\sitemap\index.js:49:45)
      at D:\学习\Hexo\wangshuai-blog\node_modules\hexo-seo\dist\src\sitemap\index.js:71:9
      at Array.forEach (<anonymous>)
      at Object.<anonymous> (D:\学习\Hexo\wangshuai-blog\node_modules\hexo-seo\dist\src\sitemap\index.js:69:8)
      at Module._compile (node:internal/modules/cjs/loader:1149:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
      at Module.load (node:internal/modules/cjs/loader:1027:32)
      at Module._load (node:internal/modules/cjs/loader:868:12)
      at Module.require (node:internal/modules/cjs/loader:1051:19)
      at require (node:internal/modules/cjs/helpers:103:18)
      at Object.<anonymous> (D:\学习\Hexo\wangshuai-blog\node_modules\hexo-seo\dist\src\html\index.js:19:33)
      at Module._compile (node:internal/modules/cjs/loader:1149:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
} Plugin load failed: %s hexo-seo
ERROR {
  err: TypeError: typeMap[type].map is not a function
      at Mime.define (D:\学习\Hexo\wangshuai-blog\node_modules\mime\Mime.js:41:36)
      at new Mime (D:\学习\Hexo\wangshuai-blog\node_modules\mime\Mime.js:12:10)
      at Object.<anonymous> (D:\学习\Hexo\wangshuai-blog\node_modules\mime\index.js:4:18)
      at Module._compile (node:internal/modules/cjs/loader:1149:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
      at Module.load (node:internal/modules/cjs/loader:1027:32)
      at Module._load (node:internal/modules/cjs/loader:868:12)
      at Module.require (node:internal/modules/cjs/loader:1051:19)
      at require (node:internal/modules/cjs/helpers:103:18)
      at Object.<anonymous> (D:\学习\Hexo\wangshuai-blog\node_modules\hexo-server\lib\middlewares\route.js:4:14)
      at Module._compile (node:internal/modules/cjs/loader:1149:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
      at Module.load (node:internal/modules/cjs/loader:1027:32)
      at Module._load (node:internal/modules/cjs/loader:868:12)
      at Module.require (node:internal/modules/cjs/loader:1051:19)
      at req (D:\学习\Hexo\wangshuai-blog\node_modules\hexo\lib\hexo\index.js:292:23)
      at D:\学习\Hexo\wangshuai-blog\node_modules\hexo-server\index.js:28:50
      at D:\学习\Hexo\wangshuai-blog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (D:\学习\Hexo\wangshuai-blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\学习\Hexo\wangshuai-blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\学习\Hexo\wangshuai-blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\学习\Hexo\wangshuai-blog\node_modules\bluebird\js\release\promise.js:649:10)
} Plugin load failed: %s hexo-server
INFO  Start processing
INFO  
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|             感谢使用 Fluid 主题 !            |
|    文档: https://hexo.fluid-dev.com/docs/    |
|                                              |
------------------------------------------------

INFO  Files loaded in 517 ms
INFO  0 files generated in 660 ms
```
I use [fluid](https://hexo.fluid-dev.com/docs/)

All my code is in [hexo-temp](https://github.com/wangshuai-007/hexo-temp)

**Comment by dimaslanjaka** [comment]
fixed at https://github.com/dimaslanjaka/hexo-seo/commit/612be9b6a323c86fcf5ed6fd553867275deaeea1
